module DemoSeed
  PASSWORD = "NomoTectLocal2026!"

  class << self
    def call
      raise "demo:seed is only available in development" unless Rails.env.development?

      results = [ "Acme Services", "Orion Support" ].each_with_index.map do |name, index|
        organization = Organization.find_or_create_by!(slug: name.parameterize) do |record|
          record.name = name
          record.locale = "en"
          record.time_zone = "UTC"
          record.theme = "system"
        end
        seed_organization(organization, suffix: index + 1)
      end

      {
        organizations: results,
        sla_target: ServiceRequests::SlaTarget.call(priority: :critical),
        extension_loaded: Extensions::Runtime.result.loaded.include?("nomotect.service-desk-sla") || ServiceRequests::SlaTarget.available?
      }
    end

    private

    def seed_organization(organization, suffix:)
      admin = find_or_create_user!("admin-#{suffix}", organization)
      agent = find_or_create_user!("agent-#{suffix}", organization)
      requester = find_or_create_user!("requester-#{suffix}", organization)
      reconcile_memberships!(organization, admin, agent, requester)

      existing = ServiceRequest.where(organization: organization).count
      if existing.positive?
        return {
          organization: organization.name,
          skipped: true,
          existing_requests: existing,
          users: [ admin.email_address, agent.email_address, requester.email_address ]
        }
      end

      requests = seed_requests(organization, admin, agent, requester)
      seed_attachments(requests)
      { organization: organization.name, users: [ admin.email_address, agent.email_address, requester.email_address ], requests: requests.size }
    end

    def find_or_create_user!(slug, organization)
      email = "#{slug}@#{organization.slug}.example.com"
      User.find_or_initialize_by(email_address: email).tap do |user|
        user.password = PASSWORD
        user.password_confirmation = PASSWORD
        user.locale = "en"
        user.time_zone = "UTC"
        user.save!
      end
    end

    def reconcile_memberships!(organization, admin, agent, requester)
      role_assignments = {
        admin => "administrator",
        agent => "support_agent",
        requester => "requester"
      }
      role_assignments.each do |user, role|
        membership = organization.memberships.find_or_initialize_by(user: user)
        membership.role = role
        membership.save!
      end
    end

    def seed_requests(organization, admin, agent, requester)
      statuses = ServiceRequest::STATUSES
      priorities = ServiceRequest::PRIORITIES
      categories = ServiceRequest::CATEGORIES
      count_per_status = 8
      service = ServiceRequests::Create.new(actor: requester)

      statuses.flat_map do |status|
        count_per_status.times.map do |index|
          priority = priorities[index % priorities.size]
          category = categories[index % categories.size]
          record = service.call(
            organization: organization,
            attributes: {
              title: "#{status.humanize} request #{index + 1} for #{organization.name}",
              description: "Seed request #{index + 1} in the #{status} state with #{category} category and #{priority} priority.",
              category: category,
              priority: priority,
              status: "open"
            }
          ).record

          advance_to!(record, status, agent)
          record
        end
      end
    end

    def advance_to!(record, status, agent)
      return if record.status == status

      record.assign_attributes(assigned_support_agent: agent)
      record.save!

      path = transition_path(record.status, status)
      path.each { |target| record.transition_to!(target) }
      record
    end

    def transition_path(from, to)
      return [ to ] if ServiceRequest::VALID_TRANSITIONS.fetch(from).include?(to)

      ServiceRequest::VALID_TRANSITIONS.fetch(from).filter_map do |intermediate|
        next unless ServiceRequest::VALID_TRANSITIONS.fetch(intermediate).include?(to)

        [ intermediate, to ]
      end.first || raise(ArgumentError, "no transition path from #{from} to #{to}")
    end

    def seed_attachments(requests)
      requests.first(6).each do |request|
        ServiceRequests::AttachFile.new(actor: request.requester).call(
          service_request: request,
          name: "evidence-#{request.identifier}.txt",
          content_type: "text/plain",
          bytes: "Evidence attachment for #{request.identifier} generated by demo:seed.\n"
        )
      rescue StandardError => error
        warn "skipped attachment for #{request.identifier}: #{error.class}"
      end
    end
  end
end
